services:
  _defaults:
    public: false
    autowire: true

  Domain\Command\:
    resource: '%kernel.project_dir%/src/Domain/Command/**/Handler.php'

  Domain\Event\:
    resource: '%kernel.project_dir%/src/Domain/Event/**/Handler.php'

  Domain\Query\:
    resource: '%kernel.project_dir%/src/Domain/Query/**/Handler.php'

  Domain\BusInterface: '@Infrastructure\Messenger\Bus'

  Infrastructure\Messenger\Bus:
    arguments:
      $commandBus: '@command.bus'
      $eventBus: '@event.bus'
      $queryBus: '@query.bus'
