changesetBaseRefs:
  - develop
  - origin/develop
  - main
  - origin/main

compressionLevel: mixed

defaultSemverRangePrefix: ""

enableGlobalCache: false

nodeLinker: pnp

yarnPath: .yarn/releases/yarn-4.0.2.cjs
