version: 2
updates:
  - package-ecosystem: npm
    directory: /apps/web
    schedule:
      interval: weekly
      time: '06:00'
      timezone: Europe/Paris
    versioning-strategy: increase
    groups:
      next:
        patterns:
          - '@types/react*'
          - next
          - react*
      eslint:
        patterns:
          - 'eslint*'

  - package-ecosystem: composer
    directory: /apps/api
    schedule:
      interval: weekly
      time: '06:00'
      timezone: Europe/Paris
    versioning-strategy: increase
    groups:
      symfony:
        patterns:
          - symfony/*
      doctrine:
        patterns:
          - doctrine/*

  - package-ecosystem: composer
    directory: /tools/deptrac
    schedule:
      interval: weekly
      time: '06:00'
      timezone: Europe/Paris
    versioning-strategy: increase

  ### DOCKERFILES ###

  - package-ecosystem: docker
    directory: /apps/api
    schedule:
      interval: weekly
      time: '06:00'
      timezone: Europe/Paris

  - package-ecosystem: docker
    directory: /apps/web
    schedule:
      interval: weekly
      time: '06:00'
      timezone: Europe/Paris

  - package-ecosystem: docker
    directory: /services/postgres
    schedule:
      interval: daily
      time: '06:00'
      timezone: Europe/Paris

  - package-ecosystem: docker
    directory: /services/nginx
    schedule:
      interval: daily
      time: '06:00'
      timezone: Europe/Paris

  - package-ecosystem: docker
    directory: /services/traefik
    schedule:
      interval: weekly
      time: '06:00'
      timezone: Europe/Paris

  - package-ecosystem: docker
    directory: /services/rabbitmq
    schedule:
      interval: weekly
      time: '06:00'
      timezone: Europe/Paris

  - package-ecosystem: docker
    directory: /tools/deptrac
    schedule:
      interval: weekly
      time: '06:00'
      timezone: Europe/Paris
