doctrine_migrations:
    migrations_paths:
        'Migration': '%kernel.project_dir%/migrations'
    enable_profiler: false
    storage:
        table_storage:
            table_name: 'migrations'
            version_column_name: 'version'
            executed_at_column_name: 'executed_at'
    all_or_nothing: true
    check_database_platform: true
