on: [push]

name: Static analysis

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  deptrac:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: build php
      run: docker compose --file docker-compose.tools.yml build deptrac
    - name: run deptrac
      run: docker compose --file docker-compose.tools.yml run --rm deptrac analyze --fail-on-uncovered

