on: [pull_request]

name: Static analysis

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  tools:
    name: ${{ matrix.tool }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tool: [deptrac]
    steps:
    - uses: actions/checkout@v4
    - name: build php
      run: docker compose --file docker-compose.tools.yml build ${{ matrix.tool }}
    - name: run ${{ matrix.tool }}
      run: docker compose --file docker-compose.tools.yml run --rm ${{ matrix.tool }}

